
const API="";const $=s=>document.querySelector(s);const money=v=>"৳"+Number(v||0).toLocaleString("en-BD");const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));let state={products:[],orders:[],agents:[],settings:{},dashboard:{}};
async function api(path,options={}){const r=await fetch(path,{...options,credentials:"include"});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
function toast(m){const e=$("#adminToast");e.textContent=m;e.className="show";clearTimeout(window.__t);window.__t=setTimeout(()=>e.className="",2500)}
async function login(e){e.preventDefault();$("#loginError").textContent="Signing in…";try{await api("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:$("#password").value.trim()})});$("#login").hidden=true;$("#app").hidden=false;await loadAll();toast("Welcome to SAREE Admin")}catch(x){$("#loginError").textContent=x.message}}
async function logout(){await api("/api/admin/logout",{method:"POST"}).catch(()=>{});location.reload()}
function setupTabs(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".panel").forEach(p=>p.classList.toggle("active",p.id===b.dataset.tab))})}
async function loadDashboard(){const d=await api("/api/admin/dashboard");state.dashboard=d;$("#revenue").textContent=money(d.revenue);$("#ordersCount").textContent=d.orders;$("#productsCount").textContent=d.products;$("#agentsCount").textContent=d.agents}
async function loadProducts(){state.products=await api("/api/admin/products");renderProducts()}
function renderProducts(){const b=$("#productTable");if(!state.products.length){b.innerHTML="<div class='empty'>No products yet.</div>";return}b.innerHTML=`<div class="table-wrap"><table><thead><tr><th>Product</th><th>Price</th><th>Category</th><th>Flags</th><th>Action</th></tr></thead><tbody>${state.products.map(p=>`<tr><td><b>${esc(p.name)}</b><small style="display:block;color:#7e8795">#${p.id}</small></td><td>${money(p.price)} ${p.old_price?`<del>${money(p.old_price)}</del>`:""}</td><td>${esc(p.category||"General")}</td><td>${p.featured?"Featured ":""}${p.is_new?"New":""}</td><td><button onclick="editProduct(${p.id})">Edit</button> <button onclick="deleteProduct(${p.id})">Delete</button></td></tr>`).join("")}</tbody></table></div>`}
window.editProduct=id=>{const p=state.products.find(x=>x.id===id),f=$("#productForm");if(!p)return;f.reset();f.elements.id.value=p.id;["name","price","old_price","category","description","tags"].forEach(k=>f.elements[k].value=p[k]??"");f.elements.featured.checked=!!p.featured;f.elements.is_new.checked=!!p.is_new;$("#pTitle").textContent="Edit Product";$("#productModal").classList.add("open")}
window.deleteProduct=async id=>{if(!confirm("Delete this product?"))return;try{await api(`/api/admin/products/${id}`,{method:"DELETE"});await loadAll();toast("Product deleted")}catch(e){toast(e.message)}}
async function saveProduct(e){e.preventDefault();const f=e.target,fd=new FormData(f),id=fd.get("id");try{await api(id?`/api/admin/products/${id}`:"/api/admin/products",{method:id?"PUT":"POST",body:fd});$("#productModal").classList.remove("open");f.reset();f.elements.id.value="";$("#pTitle").textContent="Add Product";await loadAll();toast("Product saved")}catch(x){toast(x.message)}}
async function loadOrders(){state.orders=await api("/api/admin/orders");renderOrders()}
function renderOrders(){const b=$("#orderTable");const statuses=["Pending","Confirmed","Processing","Shipped","Delivered","Cancelled"];if(!state.orders.length){b.innerHTML="<div class='empty'>No orders yet.</div>";return}b.innerHTML=`<div class="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th></tr></thead><tbody>${state.orders.map(o=>`<tr><td>SAR-${String(o.id).padStart(6,"0")}</td><td>${esc(o.customer_name)}<small style="display:block;color:#7e8795">${esc(o.phone)}<br>${esc(o.address)}</small></td><td>${money(o.total)}</td><td>${esc(o.payment_method)}</td><td><select onchange="updateOrder(${o.id},this.value)">${statuses.map(s=>`<option ${s===o.status?"selected":""}>${s}</option>`).join("")}</select></td></tr>`).join("")}</tbody></table></div>`}
window.updateOrder=async(id,status)=>{try{await api(`/api/admin/orders/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});await loadDashboard();toast("Order status updated")}catch(e){toast(e.message)}}
async function loadAgents(){state.agents=await api("/api/admin/agents");renderAgents()}
function renderAgents(){const b=$("#agentTable");if(!state.agents.length){b.innerHTML="<div class='empty'>No agents yet.</div>";return}b.innerHTML=`<div class="table-wrap"><table><thead><tr><th>Agent</th><th>WhatsApp</th><th>Messenger</th><th>Active</th><th>Action</th></tr></thead><tbody>${state.agents.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.whatsapp)}</td><td>${a.messenger_url?`<a href="${esc(a.messenger_url)}" target="_blank">Open</a>`:"—"}</td><td>${a.active?"Yes":"No"}</td><td><button onclick="editAgent(${a.id})">Edit</button> <button onclick="deleteAgent(${a.id})">Delete</button></td></tr>`).join("")}</tbody></table></div>`}
window.editAgent=id=>{const a=state.agents.find(x=>x.id===id),f=$("#agentForm");if(!a)return;f.reset();f.elements.id.value=a.id;f.elements.name.value=a.name;f.elements.whatsapp.value=a.whatsapp;f.elements.messenger_url.value=a.messenger_url||"";f.elements.active.checked=!!a.active;$("#agentModal").classList.add("open")}
window.deleteAgent=async id=>{if(!confirm("Delete this agent?"))return;try{await api(`/api/admin/agents/${id}`,{method:"DELETE"});await loadAll();toast("Agent deleted")}catch(e){toast(e.message)}}
async function saveAgent(e){e.preventDefault();const f=e.target,id=f.elements.id.value;const data={name:f.elements.name.value.trim(),whatsapp:f.elements.whatsapp.value.trim(),messenger_url:f.elements.messenger_url.value.trim(),active:f.elements.active.checked};try{await api(id?`/api/admin/agents/${id}`:"/api/admin/agents",{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});$("#agentModal").classList.remove("open");f.reset();f.elements.active.checked=true;await loadAll();toast("Agent saved")}catch(x){toast(x.message)}}
async function loadSettings(){state.settings=await api("/api/admin/settings");renderSettings()}
function renderSettings(){const f=$("#settingsForm"),s=state.settings;["store_name","logo","delivery_promise","bkash_number","nagad_number","rocket_number","payment_note"].forEach(k=>f.elements[k].value=s[k]||"");["bkash_enabled","nagad_enabled","rocket_enabled","cod_enabled"].forEach(k=>f.elements[k].checked=s[k]==="1");$("#storeTitle").textContent=s.store_name||"SAREE"}
async function saveSettings(e){e.preventDefault();const f=e.target,d={};["store_name","logo","delivery_promise","bkash_number","nagad_number","rocket_number","payment_note"].forEach(k=>d[k]=f.elements[k].value);["bkash_enabled","nagad_enabled","rocket_enabled","cod_enabled"].forEach(k=>d[k]=f.elements[k].checked);try{const r=await api("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});state.settings=r.settings||state.settings;renderSettings();$("#saved").textContent=" Saved ✓";toast("Settings synced to store");setTimeout(()=>$("#saved").textContent="",2200)}catch(x){toast(x.message)}}
async function savePassword(e){e.preventDefault();const p=e.target.elements.password.value;try{await api("/api/admin/password",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:p})});e.target.reset();toast("Password changed")}catch(x){toast(x.message)}}
async function analyzeAIProduct(e){e.preventDefault();try{const r=await api("/api/admin/ai-product",{method:"POST",body:new FormData(e.target)});renderAIResult(r.preview);toast("AI preview ready")}catch(x){toast(x.message)}}
function renderAIResult(p){$("#aiResult").innerHTML=`<div class="ai-preview"><img src="${esc(p.image)}" style="width:160px;height:160px;object-fit:cover;border-radius:12px"><h3>${esc(p.name)}</h3><p>${money(p.price)} · ${esc(p.category)}</p><p>${esc(p.description)}</p><p>${esc(p.tags)}</p><button class="gold" id="publishAI">Publish Product</button></div>`;$("#publishAI").onclick=async()=>{const fd=new FormData();Object.entries({name:p.name,price:p.price,old_price:0,category:p.category,description:p.description,tags:p.tags,image_url:p.image}).forEach(([k,v])=>fd.append(k,v));try{await api("/api/admin/products",{method:"POST",body:fd});await loadAll();$("#aiResult").innerHTML="<p>Product published successfully.</p>";toast("AI product published")}catch(e){toast(e.message)}}}
async function loadAISetup(){const s=state.settings,f=document.querySelector('#aiSetupForm');if(!f)return;['ai_q1_title','ai_q1_text','ai_q2_title','ai_q2_text','ai_q3_title','ai_q3_text','ai_q4_title','ai_q4_text','ai_q5_title','ai_q5_text'].forEach(k=>{if(f.elements[k])f.elements[k].value=s[k]||''});}
async function saveAISetup(e){e.preventDefault();const f=e.target;const d={};['ai_q1_title','ai_q1_text','ai_q2_title','ai_q2_text','ai_q3_title','ai_q3_text','ai_q4_title','ai_q4_text','ai_q5_title','ai_q5_text'].forEach(k=>d[k]=f.elements[k].value);try{let r=await api('/api/admin/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});state.settings=r.settings||state.settings;if(f.elements.image.files[0]){const fd=new FormData();fd.append('image',f.elements.image.files[0]);await api('/api/admin/ai-setup-image',{method:'POST',body:fd});state.settings=await api('/api/admin/settings');}await loadAISetup();$('#aiSaved').textContent=' Saved ✓';toast('AI shopping setup saved');setTimeout(()=>$('#aiSaved').textContent='',2200)}catch(x){toast(x.message)}}
function setupModals(){document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest(".overlay").classList.remove("open"));document.querySelectorAll(".overlay").forEach(o=>o.onclick=e=>{if(e.target===o)o.classList.remove("open")});$("#newProduct").onclick=()=>{$("#productForm").reset();$("#productForm").elements.id.value="";$("#pTitle").textContent="Add Product";$("#productModal").classList.add("open")};$("#newAgent").onclick=()=>{$("#agentForm").reset();$("#agentForm").elements.id.value="";$("#agentForm").elements.active.checked=true;$("#agentModal").classList.add("open")}}
async function loadAll(){await Promise.all([loadDashboard(),loadProducts(),loadOrders(),loadAgents(),loadSettings()]);await loadAISetup();$("#storeLink").href="/"}
document.addEventListener("DOMContentLoaded",async()=>{setupTabs();setupModals();$("#loginForm").addEventListener("submit",login);$("#logout").onclick=logout;$("#refresh").onclick=()=>loadAll().then(()=>toast("Refreshed")).catch(e=>toast(e.message));$("#productForm").addEventListener("submit",saveProduct);$("#agentForm").addEventListener("submit",saveAgent);$("#settingsForm").addEventListener("submit",saveSettings);$("#passwordForm").addEventListener("submit",savePassword);$("#aiForm").addEventListener("submit",analyzeAIProduct);$("#aiSetupForm").addEventListener("submit",saveAISetup);try{await api("/api/admin/me");$("#login").hidden=true;$("#app").hidden=false;await loadAll()}catch(e){$("#login").hidden=false;$("#app").hidden=true}});
