let products=[],cart=JSON.parse(localStorage.getItem('sareeCart')||'[]'),settings={};
const $=s=>document.querySelector(s),money=v=>'৳'+Number(v||0).toLocaleString('en-BD');
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth'})}
async function load(){settings=await fetch('/api/settings').then(r=>r.json());products=await fetch('/api/products').then(r=>r.json());renderCats();renderProducts(products);updateCart()}
function renderCats(){const cats=[['🧵','Katan'],['🌸','Jamdani'],['✨','Organza'],['🌿','Cotton'],['👑','Premium'],['💜','Festive']];$('#categories').innerHTML=cats.map(c=>`<div class="cat" onclick="filterCat('${c[1]}')"><div class="circle">${c[0]}</div><span>${c[1]}</span></div>`).join('')}
function renderProducts(list){$('#productGrid').innerHTML=list.map(p=>`<article class="card"><div class="card-img"><img src="${esc(p.image)}" onerror="this.src='/assets/product-placeholder.svg'">${p.is_new?'<span class="badge new">New</span>':p.featured?'<span class="badge">Hot</span>':''}<button class="heart">♡</button></div><div class="card-body"><h3>${esc(p.name)}</h3><div class="price">${money(p.price)} ${p.old_price?`<del>${money(p.old_price)}</del>`:''}</div><div class="rating">★ 4.9 · Premium quality</div><div class="actions"><button onclick="addCart(${p.id})">Add to Cart</button><button class="buy" onclick="buyNow(${p.id})">Buy Now</button></div></div></article>`).join('')||'<p>No product found.</p>'}
function filterCat(c){document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.dataset.cat===c));renderProducts(c==='all'?products:products.filter(p=>p.category===c))}
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>filterCat(b.dataset.cat));
function searchProducts(){const q=$('#search').value.toLowerCase().trim();renderProducts(products.filter(p=>(p.name+' '+p.category+' '+p.tags+' '+p.description).toLowerCase().includes(q)))}
$('#search').addEventListener('keydown',e=>{if(e.key==='Enter')searchProducts()});
function saveCart(){localStorage.setItem('sareeCart',JSON.stringify(cart));updateCart()}
function addCart(id){const p=products.find(x=>x.id==id);if(!p)return;const x=cart.find(i=>i.id==id);x?x.qty++:cart.push({id:p.id,name:p.name,price:p.price,image:p.image,qty:1});saveCart();toast('Cart-এ যোগ হয়েছে')}
function buyNow(id){addCart(id);openCart()}
function updateCart(){$('#cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0)}
function openCart(){show(`<h2>আপনার Cart</h2>${cart.length?cart.map(i=>`<div class="cart-item"><img src="${esc(i.image)}"><div style="flex:1"><b>${esc(i.name)}</b><div>${money(i.price)}</div><div class="qty"><button onclick="changeQty(${i.id},-1)">−</button>${i.qty}<button onclick="changeQty(${i.id},1)">+</button></div></div></div>`).join('')+`<h3>Total: ${money(cart.reduce((a,x)=>a+x.price*x.qty,0))}</h3><button class="primary" onclick="checkout()">Checkout →</button>`:'<p>Cart খালি।</p>'}`)}
function changeQty(id,d){const x=cart.find(i=>i.id==id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(i=>i.id!=id);saveCart();openCart()}
function checkout(){if(!cart.length)return;const total=cart.reduce((a,x)=>a+x.price*x.qty,0);show(`<h2>Checkout</h2><form class="form" id="checkoutForm"><input name="customer_name" placeholder="আপনার নাম" required><input name="phone" placeholder="মোবাইল নম্বর" required><textarea name="address" placeholder="পূর্ণ ঠিকানা" required></textarea><select name="payment_method" id="pay" required><option value="">Payment Method</option>${settings.bkash_enabled==='1'?'<option>bKash</option>':''}${settings.nagad_enabled==='1'?'<option>Nagad</option>':''}${settings.rocket_enabled==='1'?'<option>Rocket</option>':''}${settings.cod_enabled==='1'?'<option>Cash on Delivery</option>':''}</select><input name="payment_number" id="payNum" placeholder="Payment number" readonly><input name="transaction_id" placeholder="Transaction ID (COD হলে লাগবে না)"><button class="primary">অর্ডার Confirm • ${money(total)}</button></form>`);$('#pay').onchange=()=>{$('#payNum').value=settings[$('#pay').value.toLowerCase()+'_number']||''};$('#checkoutForm').onsubmit=submitOrder}
async function submitOrder(e){e.preventDefault();const f=new FormData(e.target),total=cart.reduce((a,x)=>a+x.price*x.qty,0);const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(f),total,items:cart})}).then(x=>x.json());if(r.error)return toast(r.error);cart=[];saveCart();show(`<h2>অর্ডার সফল 🎉</h2><p>আপনার Order ID: <b>${r.public_id}</b></p><p>Status: Pending</p><button class="primary" onclick="closeModal()">Done</button>`)}
function openTrack(){show(`<h2>Order Tracking</h2><form class="form" id="track"><input name="id" placeholder="SAR-000001" required><button class="primary">Track Order</button></form><div id="trackResult"></div>`);$('#track').onsubmit=async e=>{e.preventDefault();const id=new FormData(e.target).get('id');const r=await fetch('/api/orders/track/'+encodeURIComponent(id)).then(x=>x.json());$('#trackResult').innerHTML=r.error?`<p>${esc(r.error)}</p>`:`<p><b>${esc(r.public_id)}</b><br>Status: ${esc(r.status)}<br>Total: ${money(r.total)}</p>`}}
function quickCards(){const qs=[1,2,3,4,5].map(i=>({title:settings['ai_q'+i+'_title'],text:settings['ai_q'+i+'_text']})).filter(x=>x.title);return qs.map(q=>`<button class="ai-quick" data-q="${esc(q.title)}">${esc(q.title)}</button>`).join('')}
function openChat(){show(`<div class="chat-head"><div><span class="eyebrow">SAREE SHOPPING ASSISTANT</span><h2>🤖 SAREE AI</h2></div><span class="live-dot">● Online</span></div><div class="ai-quick-row">${quickCards()}</div><div id="chatLog" class="chat-log"><div class="bubble ai"><b>SAREE:</b> আসসালামু আলাইকুম ❤️ SAREE-তে আপনাকে স্বাগতম। আমি product খুঁজে দিতে, availability বলতে এবং order নিতে পারি।</div></div><div class="chat-tools"><label class="photo-btn">📷 Product Photo<input id="chatImage" type="file" accept="image/*" hidden></label><form class="chat-form" id="chatForm"><input name="message" autocomplete="off" placeholder="SAREE সম্পর্কে জিজ্ঞেস করুন বা order বলুন…" required><button>Send</button></form></div>`);document.querySelectorAll('.ai-quick').forEach(b=>b.onclick=()=>sendChat(b.dataset.q));$('#chatForm').onsubmit=e=>{e.preventDefault();const m=new FormData(e.target).get('message');e.target.reset();sendChat(m)};$('#chatImage').onchange=e=>{if(e.target.files[0])sendChatImage(e.target.files[0])}}
async function sendChat(message){const log=$('#chatLog');if(!log)return;log.innerHTML+=`<div class="bubble user"><b>You:</b> ${esc(message)}</div>`;log.scrollTop=log.scrollHeight;try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})}).then(x=>x.json());if(r.error)throw Error(r.error);log.innerHTML+=`<div class="bubble ai"><b>SAREE:</b> ${esc(r.reply).replace(/\n/g,'<br>')}${r.order_id?`<br><strong>Order ID: ${esc(r.order_id)}</strong>`:''}</div>`;if(r.product)log.innerHTML+=`<div class="chat-product"><img src="${esc(r.product.image)}"><div><b>${esc(r.product.name)}</b><br>${money(r.product.price)}<br><button onclick="addCart(${r.product.id})">Add to Cart</button></div></div>`;if(r.proof_image)log.innerHTML+=`<img class="proof-img" src="${esc(r.proof_image)}">`;log.scrollTop=log.scrollHeight}catch(e){log.innerHTML+=`<div class="bubble ai">দুঃখিত ❤️ আবার চেষ্টা করুন।</div>`}}
async function sendChatImage(file){const log=$('#chatLog');log.innerHTML+=`<div class="bubble user">📷 Product photo sent</div>`;const fd=new FormData();fd.append('image',file);try{const r=await fetch('/api/chat-image',{method:'POST',body:fd}).then(x=>x.json());log.innerHTML+=`<div class="bubble ai"><b>SAREE:</b> ${esc(r.reply)}</div>`;if(r.product)log.innerHTML+=`<div class="chat-product"><img src="${esc(r.product.image)}"><div><b>${esc(r.product.name)}</b><br>${money(r.product.price)}<br><button onclick="addCart(${r.product.id})">Add to Cart</button></div></div>`}catch(e){log.innerHTML+=`<div class="bubble ai">ছবিটি process করা যায়নি। আবার দিন।</div>`}log.scrollTop=log.scrollHeight}
function contactAgent(){const a=settings.whatsapp||'';window.open(a?'https://wa.me/'+a.replace(/\D/g,''):'https://wa.me/','_blank')}
function show(html){$('#modalBox').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()}
function toast(m){const x=document.createElement('div');x.textContent=m;x.style.cssText='position:fixed;left:50%;bottom:110px;transform:translateX(-50%);background:#111;color:#fff;padding:12px 18px;border-radius:12px;z-index:50';document.body.appendChild(x);setTimeout(()=>x.remove(),1800)}
load().catch(()=>toast('SAREE Store API unavailable. Backend চালু করুন।'));
